import { env } from '../env';

export const CREDENTIALS = env.CREDENTIALS;
export const { 
    NODE_ENV, PORT, SECRET_KEY, ADMIN_API_KEY, LOG_FORMAT, LOG_DIR, ORIGINS,
    DB_HOST, DB_URL, DB_PORT, DB_NAME, DB_USERNAME, DB_PASSWORD,
    RAZORPAY_KEY, RAZORPAY_SECRET,
    GOOGLE_CLIENT_SECRET, GOOGLE_CLIENT_ID, OPENAI_KEY, OPENAI_MODEL_NAME, MAXIMUM_CHAT_BUFFER
} = env;
